FROM debian:stable-slim

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    dnsutils \
    git \
    gnupg \
    iputils-ping \
    net-tools \
    nodejs \
    openssh-client \
    openssl \
    procps \
    psmisc \
    rsync \
    vim-nox \
    whois \
&& rm -rf /var/lib/apt/lists/*

COPY server.js .
EXPOSE 8080

RUN groupadd -g 999 -r k8s-debug && useradd --no-log-init -u 999 -r -g k8s-debug k8s-debug
USER 999:999

CMD nodejs server.js
