name: Build & Push Images

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Quay.io 
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push k8s-debug:nonroot
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-nonroot
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            quay.io/filiphavlicek/k8s-debug:nonroot
            quay.io/filiphavlicek/k8s-debug:latest
            flphvlck/k8s-debug:nonroot
            flphvlck/k8s-debug:latest

      - name: Build and push k8s-debug:root
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-root
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            quay.io/filiphavlicek/k8s-debug:root
            flphvlck/k8s-debug:root
